# Generated by Django 2.0.5 on 2019-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('ud', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('demand', models.CharField(default='无要求', max_length=20)),
                ('time', models.CharField(max_length=16)),
                ('work_tepy', models.CharField(max_length=10)),
                ('work_time', models.CharField(max_length=6)),
                ('teacher_name', models.CharField(max_length=10)),
                ('Impatient', models.CharField(default='普', max_length=10)),
                ('photos', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(default=2, max_length=2)),
                ('peoples', models.CharField(max_length=10)),
            ],
        ),
    ]
