# Generated by Django 2.0.5 on 2019-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
