# Generated by Django 2.0.5 on 2019-03-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_auto_20190301_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number_peoplr',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
