# Generated by Django 2.0.5 on 2019-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20190302_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
