# Generated by Django 2.0.5 on 2019-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_auto_20190302_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.CharField(max_length=35),
        ),
    ]
