# Generated by Django 2.0.5 on 2019-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_auto_20190303_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='teacher_name',
            field=models.CharField(max_length=20),
        ),
    ]
